"""empty message

Revision ID: 152d8e7f2037
Revises: 2affb78c8689
Create Date: 2019-07-05 09:18:41.414968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152d8e7f2037'
down_revision = '2affb78c8689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'updated_at')
    # ### end Alembic commands ###
