"""empty message

Revision ID: bba98862e706
Revises: 130f38c48710
Create Date: 2019-06-15 19:11:17.818801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba98862e706'
down_revision = '130f38c48710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donation_image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'donation_image')
    # ### end Alembic commands ###
